/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "AccountConfigurationPluginHostProtocol-Protocol.h"

@class AccountConfiguration;

@protocol AccountConfigurationPluginProtocol <NSCopying, NSObject>
- (id)view;
- (BOOL)hasLoginSheet;
- (void)beginLoginSheetModalForWindow:(id)arg1 modalDelegate:(id)arg2 didEndSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (void)beginPasswordSheetModalForWindow:(id)arg1 modalDelegate:(id)arg2 didEndSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (id)accountTypeIdentifier;
- (id)accountTypeIcon;
- (id)accountTypeIconOfSize:(unsigned long long)arg1;
- (id)displayNameForAccountConfiguration:(id)arg1;
- (id)accountTypeDisplayName;
- (void)beginEditingConfiguration:(id)arg1;
- (void)initializeConfiguration:(id)arg1;
- (void)endEditingConfiguration;
- (id)keychainURLForAccountConfiguration:(id)arg1;
- (id)settingsDictionaryForUnsavedChangesCheck:(id)arg1;
- (BOOL)canEndEditingConfiguration;
- (void)prepareAccountConfigurationForDisplay:(id)arg1;
- (BOOL)validateStoredCredentialsForAccountConfiguration:(id)arg1;
@property(retain) AccountConfiguration *editedConfiguration;
@property(readonly) long long displaySortPriority;
@property BOOL networkOperationInProgress;
@property (retain) id <AccountConfigurationPluginHostProtocol> pluginManager;
@end

