/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "AccountConfigurationManagerProtocol-Protocol.h"

@interface AccountConfiguration : NSObject <NSCopying>
{
    NSMutableDictionary *settings;
    NSMutableDictionary *snapshot;
    NSString *displayName;
    NSString *accountType;
    NSString *accountIdentifier;
    NSString *password;
    long long updateInterval;
    NSDate *lastUpdateTime;
    BOOL didChangePassword;
    BOOL isTemporary;
    BOOL isDisabled;
    id <AccountConfigurationManagerProtocol> manager;
}

+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)keyPathsForValuesAffectingHasDisplayName;
+ (id)keyPathsForValuesAffectingNextUpdateTimeLabel;
+ (id)keyPathsForValuesAffectingNextUpdateTime;
- (id)init;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) NSImage *accountTypeIcon;
@property(readonly) NSString *accountTypeDisplayName;
- (id)plugin;
- (id)dictionaryRepresentation;
- (void)applyDictionaryRepresentation:(id)arg1;
- (void)beginEditing;
- (void)endEditing;
- (void)clearDirty;
@property(readonly) BOOL dirty;
@property(readonly) BOOL empty;
- (void)cancelEditing;
@property(retain) NSString *password; // @synthesize password;
- (id)description;
@property(retain) NSString *displayName; // @synthesize displayName;
@property(readonly) BOOL hasDisplayName;
@property(readonly) NSDate *nextUpdateTime;
@property(readonly) NSString *nextUpdateTimeLabel;
@property long long updateInterval; // @synthesize updateInterval;
@property(retain) NSDate *lastUpdateTime; // @synthesize lastUpdateTime;
@property(retain) id <AccountConfigurationManagerProtocol> manager; // @synthesize manager;
@property BOOL isDisabled; // @synthesize isDisabled;
@property BOOL isTemporary; // @synthesize isTemporary;
@property BOOL didChangePassword; // @synthesize didChangePassword;
@property(retain) NSString *accountIdentifier; // @synthesize accountIdentifier;
@property(retain) NSString *accountType; // @synthesize accountType;
@property(retain) NSMutableDictionary *snapshot; // @synthesize snapshot;
@property(retain) NSMutableDictionary *settings; // @synthesize settings;

@end

