/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSOperation.h"

@class AccountConfiguration, NSObject<AccountConfigurationManagerProtocol>, NSString;

@interface AccountConfigurationProfileInformationDownloadOperation : NSOperation
{
    NSObject<AccountConfigurationManagerProtocol> *manager;
    AccountConfiguration *configuration;
    NSString *displayName;
}

- (void)dealloc;
- (void)main;
- (void)updateProfileData;
@property(retain) NSString *displayName; // @synthesize displayName;
@property(retain) AccountConfiguration *configuration; // @synthesize configuration;
@property(retain) NSObject<AccountConfigurationManagerProtocol> *manager; // @synthesize manager;

@end

